# Generated by Django 4.2.9 on 2026-02-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendly_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinglog',
            name='calendly_event_uri',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='bookinglog',
            name='guest_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='bookinglog',
            name='guest_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bookinglog',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='bookinglog',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('canceled', 'Canceled'), ('rescheduled', 'Rescheduled')], db_index=True, default='scheduled', max_length=20),
        ),
    ]
