# Generated by Django 4.2.9 on 2026-02-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitedContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inviter_phone', models.CharField(db_index=True, max_length=20)),
                ('invited_phone', models.CharField(db_index=True, max_length=20)),
                ('invited_name', models.CharField(max_length=200)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Invited Contact',
                'verbose_name_plural': 'Invited Contacts',
                'ordering': ['-created_at'],
                'unique_together': {('inviter_phone', 'invited_phone')},
            },
        ),
    ]
