# Generated by Django 4.2.9 on 2026-02-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_invitedcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedcontact',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('invited', 'Invited'), ('confirmed', 'Confirmed')], db_index=True, default='pending', max_length=20),
        ),
    ]
