# Generated by Django 4.2.9 on 2026-02-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_invitedcontact_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipphone',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
